name: 'Generate a latest.yml for an artifact'
description: 'Electron auto updater needs the latest.yml file to check'
author: 'y-not-u'
inputs:
  artifact:
    description: 'Artifact file'
    required: true
  version:
    description: 'New version'
    required: true
  hash-type:
    description: 'Hash type' 
    default: 'sha512'
  yml-file:
    description: 'yaml file name'
    default: 'latest.yml'
  staging-percentage:
    description: 'Staging Percentage'
    default: 100

runs:
  using: 'node16'
  main: 'dist/index.js'
