name: Release

on: 
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create artifact file
        run: |
          echo "Lorem ipsum dolor sit amet" > file1.txt
          echo "Lorem ipsum dolor sit amet" > file2.md
      - uses: y-not-u/electron-builder-latest-yml-action@v1
        with:
          version: ${{github.ref_name}}
          artifact: file1.txt
          hash-type: sha512
          staging-percentage: 80
      - uses: y-not-u/electron-builder-latest-yml-action@v1
        with:
          version: ${{github.ref_name}}
          artifact: "*.md"
          hash-type: sha256
          staging-percentage: 10
          yml-file: latest-md.yml
      - uses: actions/upload-artifact@v2
        with:
          name: latest.yml
          path: 
            latest.yml
            latest-md.yml
